version: "3.7"

services:
  database: 
    image: postgres
    container_name: andrea-contas-database
    restart: always
    ports: 
      - 8083:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=andrea-contas
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: andrea-contas
    restart: always
    environment:
      - DATABASE_URL=postgresql://docker:ignite@andrea-contas-database:5432/andrea-contas
    ports: 
      - 9999:9999
      - 6000:6000
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database




volumes:
  pgdata:
    driver: local